### ISSUE TITLE
Add partitioning function for OneNote documents

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#1017] opened 2023-08-01 19:08 UTC
The goal of this issue is to add the ability to process [Microsoft OneNote](https://en.wikipedia.org/wiki/Microsoft_OneNote) files. These files have a `.one` extension.

**Comment by orlandounstructured** [comment] 2024-02-08 23:42
Closing because longer than 180 days;
reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-08 23:42 UTC
Labels: enhancement
