### ISSUE TITLE
bug/Reading File When IO[bytes] file param is passed , not file name

### ISSUE THREAD

**Issue by narenderAwen** [Unstructured-IO/unstructured#2308] opened 2023-12-21 14:41 UTC
**Describe the bug**
I am using the partition_pdf function, i give the file (IO[bytes]) object as argument in file param, not filename or url. I am recieving file from some remote source, encoded to base 64, i am converting it to BytesIO() , then give as file, i also update its filename arg (because i need to keep it for record downstream), now according to code and error stack i have mentioned below, there is a function which fetches modify date by directly reading file from fs, which i obviously not present
```python
datetime.fromtimestamp(os.path.getmtime(filename))
``` 
So i guess i cant pass file as arg if its not in file system, is this by design, and if yes then how am i supposed to process files fetched from other sources, not necessarily present in my file system

**To Reproduce**
Just pass a BytesIO() object with file name set, and observe

**Expected behavior**
Should ideally not throw an error

Below is the stack trace, i also raised a PR if you like to review and merge.
[https://github.com/Unstructured-IO/unstructured/pull/2307](https://github.com/Unstructured-IO/unstructured/pull/2307)
**Screenshots**
```
  File "/Users/narenderawen/AwenDev/eLLM/eLLM/parsers/pdfparser.py", line 39, in parse
    elements_raw=partition_pdf(
                 ^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/documents/elements.py", line 503, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 591, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 546, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/chunking/title.py", line 241, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 176, in partition_pdf
    return partition_pdf_or_image(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 246, in partition_pdf_or_image
    last_modification_date = get_the_last_modification_date_pdf_or_img(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 218, in get_the_last_modification_date_pdf_or_img
    last_modification_date = get_last_modified_date_from_file(file=file)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/partition/common.py", line 98, in get_last_modified_date_from_file
    modify_date = get_last_modified_date(filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/narenderawen/AwenDev/eLLM/venv/lib/python3.11/site-packages/unstructured/partition/common.py", line 84, in get_last_modified_date
    modify_date = datetime.fromtimestamp(os.path.getmtime(filename))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 55, in getmtime
FileNotFoundError: [Errno 2] No such file or directory: '/somepath/filename.pdf'
```

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**

**Comment by christinestraub** [comment] 2024-01-11 22:59
Hi @narenderAwen, can you provide a code snippet that you're using? I tested partition_pdf with the following code snippet but could not see any errors.
 
```
with open("dist/docs/img_1_b64.txt", "r") as f:
    image_b64_str = f.read()
    image_bytesio = BytesIO(b64decode(image_b64_str))
    elements = partition_pdf(
        file=image_bytesio,
        strategy=strategy,
    )
```

**Comment by KevinJBoyer** [comment] 2024-02-02 18:31
Also running this issue. @christinestraub's code above works because there really is a file at `dist/docs/pdf_1_b64.txt` on disk to be read. The issue happens when the file is present only in memory and not on disk at all.

In my case I'm trying to use `unstructured` with Streamlit's [file_uploader widget](https://docs.streamlit.io/library/api-reference/widgets/st.file_uploader), so I am also interested in understanding this question:

> So i guess i cant pass file as arg if its not in file system, is this by design, and if yes then how am i supposed to process files fetched from other sources, not necessarily present in my file system

**Comment by KevinJBoyer** [comment] 2024-02-02 18:56
Aha. In `get_the_last_modification_date_pdf_or_img` (I happen to be using PDFs) we have:

```
    if not file and filename:
        last_modification_date = get_last_modified_date(filename=filename)
    elif not filename and file:
        last_modification_date = get_last_modified_date_from_file(file=file)
```

And in `get_last_modified_date_from_file`, we have:

```
    filename = None
    if hasattr(file, "name"):
        filename = file.name

    if not filename:
        return None

    modify_date = get_last_modified_date(filename)
```

I'm not sure if strictly speaking it's correct to assume that `if hasattr(file, "name")` passes, this is a file that can be read from local disk. But I don't have a sophisticated enough understanding of Python IO conventions to be sure. In the meantime, you can work around this by dropping the attribute from the file explicitly:

```
  delattr(file, 'name')
  elements = partition(file=files)
```

**Comment by scanny** [comment] 2024-03-05 22:35
If the `filename` argument is provided to a partitioner it is assumed you want to read that file from the local filesystem at the path provided. If you provide a `file` argument (a file-like object like `io.BytesIO` for example) then that will be used as the source for the document.

In that case, in order to provide a file name for metadata purposes you can assign it to the `.name` attribute of the file-like object before the partition call, like:
```python
file = io.BytesIO(bytes)
file.name = "path_I_want/in_metadata.pdf"
elements = partition_...(file=file, ...)
```

**Comment by scanny** [comment] 2024-03-05 22:36
Closing this as it seems to be resolved, feel free to reopen if you're still having trouble :)

**Comment by KevinJBoyer** [comment] 2024-03-05 23:23
@scanny I don't think this should be closed.

Maybe I'm misunderstanding what you wrote, but the issue is not from passing in the `filename` argument. The issue is that even when this is _not_ passed, the presence of the name attribute will cause result in an attempt to read the file as if it exists on disk. E.g., your example code will crash if there is no actual `path_I_want/in_metadata.pdf` on the filesystem.

**Comment by scanny** [comment] 2024-03-06 00:39
Ah, yes, I see it now. Okay, that won't do. I'll pick this one up :)

**Comment by scanny** [comment] 2024-03-06 00:52
Yep, sure enough. This reproduces the error:
```python
"""Reproduce error reported in https://github.com/Unstructured-IO/unstructured/issues/2308."""

from __future__ import annotations

import io

from unstructured.partition.pdf import partition_pdf

# -- load from file-like object with name set --
with open("example-docs/DA-1p.pdf", "rb") as f:
    file = io.BytesIO(f.read())
file.name = "_scratch/badda.bang.pdf"

partition_pdf(file=file)

>>> FileNotFoundError: [Errno 2] No such file or directory: '_scratch/badda.bang.pdf'
```

**Closed** 2024-03-07 19:33 UTC
Labels: bug
