### ISSUE TITLE
Some PDF's with scanned images return empty elements

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#346] opened 2023-03-07 01:32 UTC
For some PDF's, `partition()` in `unstructured.partition.pdf` returns whitespace-only elements even though a JPG or PNG -exported file of the same PDF has elements with text successfully returned by `partition_image()` in `unstructured.partition.image`.

![image](https://user-images.githubusercontent.com/28578599/223296020-5100a958-4608-48ff-8115-79d4a9d81951.png)

**Definition of Done**

* Test added where [this PDF](https://azureunstructured1.blob.core.windows.net/container1/IRS-form-1987.pdf) succeeds with the bug fix.

**Comment by awalker4** [comment] 2023-03-09 17:46
It may take some digging, but there are lots of old scans of research papers at this [ftp site](https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/00/). Might be a good source for reproducing.

**Comment by cragwolfe** [comment] 2023-03-15 04:04
I juste update the description to reference https://azureunstructured1.blob.core.windows.net/container1/IRS-form-1987.pdf which includes a PDF that fails.

**Comment by qued** [comment] 2023-05-03 23:57
After some investigation:

The reference PDF contains 2 pages, each of which contains a single full-page black and white image that's referenced as a PDF XObject.

The issue is caused by the particulars of the PDF code that references the internal image and `pdfminer.six`'s parsing logic. The PDF code on the first page (for example) ends with the phrase `/Im1 Do`, and there is no character after `Do`. `pdfminer.six` requires one of a collection of particular characters to terminate a keyword, so `pdfminer.six` considers the keyword non-terminating and does not parse it, so the image is not rendered internally. This does not seem to be the case with other readers such as Acrobat Reader, Chrome, and Firefox, so I'm not sure if the PDF is malformed and other readers are more forgiving, or this is an error in `pdfminer.six`'s interpretation of the PDF spec.

Either way, the PDF parses correctly with a small change to the `pdfminer.six` code, so I plan to float a PR to that library.

**Comment by qued** [comment] 2023-05-04 21:25
Closing as fixed. PR [#98](https://github.com/Unstructured-IO/unstructured-inference/pull/98) fixes the issue in `unstructured-inference`. I thought changes were needed in this repo but on reflection it's not clear that the `fast` strategy needs an update. I'd at least like to see some example docs that fail on `fast` first (the example doc linked fails on `fast`, but because it doesn't contain any embedded text, not because of this issue).

To get the fix, update to `unstructured-inference>=0.4.3`.

**Closed by qued** 2023-05-04 21:25 UTC
Labels: bug
