### ISSUE TITLE
Unable to parse some HTMLs

### ISSUE THREAD

**Issue by ji21** [Unstructured-IO/unstructured#502] opened 2023-04-19 19:47 UTC
Hi there, I'm using llama-index which uses unstructuredIO to parse HTML, but very often I'm getting errors. For example https://gpt-index.readthedocs.io/en/latest/getting_started/installation.html doesn't work, but google.com does.

This is the error:
```
INFO:unstructured:Reading document from string ...
INFO:unstructured:Reading document ...
Traceback (most recent call last):
  File "/Users/user/crawl/index.py", line 14, in <module>
    html = loader.load_data(file=Path(f'./output1.html'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/crawl/venv/lib/python3.11/site-packages/llama_index/readers/llamahub_modules/file/unstructured/base.py", line 36, in load_data
    elements = partition(str(file))
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/crawl/venv/lib/python3.11/site-packages/unstructured/partition/auto.py", line 86, in partition
    elements = partition_html(
               ^^^^^^^^^^^^^^^
  File "/Users/user/crawl/venv/lib/python3.11/site-packages/unstructured/partition/html.py", line 85, in partition_html
    layout_elements = document_to_element_list(document, include_page_breaks=include_page_breaks)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/crawl/venv/lib/python3.11/site-packages/unstructured/partition/common.py", line 71, in document_to_element_list
    num_pages = len(document.pages)
                    ^^^^^^^^^^^^^^
  File "/Users/user/crawl/venv/lib/python3.11/site-packages/unstructured/documents/xml.py", line 52, in pages
    self._pages = self._read()
                  ^^^^^^^^^^^^
  File "/Users/user/crawl/venv/lib/python3.11/site-packages/unstructured/documents/html.py", line 101, in _read
    etree.strip_elements(self.document_tree, ["script"])
  File "src/lxml/cleanup.pxi", line 100, in lxml.etree.strip_elements
  File "src/lxml/apihelpers.pxi", line 41, in lxml.etree._documentOrRaise
TypeError: Invalid input object: NoneType
```

Thanks!

**Comment by MthwRobinson** [comment] 2023-04-20 13:39
@ji21 - Thanks for reporting this! Could you confirm what version of `unstructured` you're running? The following works for me on `0.5.13`.

```python
from unstructured.partition.auto import partition

url = "https://gpt-index.readthedocs.io/en/latest/getting_started/installation.html"
elements = partition(url=url)
```

**Comment by LaverdeS** [comment] 2023-04-21 15:52
Hey @ji21 I downloaded the html of the url you provided and executed (using `0.5.14`):

```python
from unstructured.partition.auto import partition
elements = partition(file=open('output.html', 'r'))
```

works fine, I got a bunch of `Unstructured` elements as the output as expected. Also confirmed as @MthwRobinson [here](https://github.com/Unstructured-IO/unstructured/issues/502#issuecomment-1516348691) and also works. Just in case I also executed successfully:

```python
elements = partition(str(Path(f'./output.html')))
```

Can you please check if this persist when upgrading to the most recent version of `unstructured`?

**Comment by MthwRobinson** [comment] 2023-04-24 20:51
Going to close this one for now since we've been unable to replicate the error on the `unstructured` side. Happy to reopen this if we're able to reproduce.

**Closed by MthwRobinson** 2023-04-24 20:51 UTC
Labels: bug
