### ISSUE TITLE
bug/ingest tests ignored error in CI

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#974] opened 2023-07-25 19:00 UTC
There is an error consistently happening in the ingest tests in CI that seems to be ignored, per the screen shot. Two issues:

1/ it shouldn't be happening in the first place

2/ if there is failure in this script, it probably should have caused the top level [test-ingest.sh ](https://github.com/Unstructured-IO/unstructured/blob/main/test_unstructured_ingest/test-ingest.sh) to immediately fail.

![image](https://github.com/Unstructured-IO/unstructured/assets/28578599/0212aff1-d427-4804-839a-fe8f1bbf7cd7)

**Comment by orlandounstructured** [comment] 2024-02-08 23:32
Closing because longer than 180 days; reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-08 23:32 UTC
Labels: bug
