### ISSUE TITLE
bug/Partition_docx is not working as expected; giving 0 length elements list

### ISSUE THREAD

**Issue by AlokRanjanSwain** [Unstructured-IO/unstructured#2612] opened 2024-03-05 09:12 UTC
**Describe the bug**
I am not able to load elements from a docx file, 
I am at the latest version of unstructured 

**To Reproduce**
[sample4.docx](https://github.com/Unstructured-IO/unstructured/files/14492946/sample4.docx)

```python 
docx_file = "./sample4.docx"
docx_elements = partition_docx(
    filename=docx_file,                  
    infer_table_structure= True,
    chunking_strategy="by_title",
)
print(len(docx_elements))
```
It is giving me `0` elements. 

I don't know where I am doing wrong. 

My python-docx is v 1.1.0

**Comment by scanny** [comment] 2024-03-05 19:49
Hmm, I'm getting `len(docx_elements) == 1484` for that call, so seems to be working fine.

Are you maybe looking at an older version of the file or didn't save it after pasting in the content?

**Comment by scanny** [comment] 2024-03-05 19:51
@AlokRanjanSwain closing this for now since I can't reproduce, but don't hesitate to reopen if you find more to go on :)

**Closed by scanny** 2024-03-05 19:51 UTC
Labels: bug
