### ISSUE TITLE
bug/pdf_page_content_contains_cid_values

### ISSUE THREAD

**Issue by MyIsaak** [Unstructured-IO/unstructured#1093] opened 2023-08-11 02:44 UTC
**Describe the bug**
The PDF parser does not correctly parse content when it contains special characters (e.g., umlauts). Instead, it displays (cid:123) where 123 is an example CID number.

**To Reproduce**
[ASM-U.pdf](https://github.com/Unstructured-IO/unstructured/files/12318269/ASM-U.pdf)
```python
from langchain.document_loaders import UnstructuredFileLoader
docs = UnstructuredFileLoader(file.path).load()
```

**Expected behavior**
The expected behavior is for the PDF parser to correctly parse special characters and display the corresponding Unicode characters instead of (cid:123).

**Environment Info**
OS version:  Windows-10-10.0.22621-SP0
Python version:  3.11.3
unstructured version:  0.8.8
unstructured-inference version:  0.5.7
pytesseract version:  0.3.10
Torch version:  2.0.1
Detectron2 is not installed
PaddleOCR is not installed

**Comment by orlandounstructured** [comment] 2024-02-09 00:02
Closing because longer than 180 days;
reopen with comment if the issue is still relevant

**Closed** 2024-02-09 00:02 UTC
Labels: bug
