### ISSUE TITLE
bug: partition_image returns elements in different orders for .png and .jpg files

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#2452] opened 2024-01-24 17:05 UTC
**Describe the bug**
Using `example-docs/DA-1p` as a test document, I created .png and .jpg copies and ran both through `partition_image`. They return the same elements, but some of the elements are in different orders.

**To Reproduce**
```
from unstructured.partition.image import partition_image

jpg_filename = "example-docs/DA-1p.jpg"
png_filename = "example-docs/DA-1p.png"

jpg_elements = partition_image(jpg_filename)
png_elements = partition_image(png_filename)

for i in range(len(png_elements)):
	print(png_elements[i].text == jpg_elements[i].text)
```

**Expected behavior**
I would expect the same output to be returned by partitioning the same document in different formats (.pdf, .jpg, .png, etc.)
Note: the elements returned by .jpg and .png are different from the elements returned by partitioning this document in .pdf format, but that should be opened as a separate issue.

**Environment Info**
OS version:  macOS-14.1.2-arm64-arm-64bit
Python version:  3.10.13
unstructured version:  0.11.6.dev3
unstructured-inference version:  0.7.23
pytesseract version:  0.3.10
Torch version:  2.1.1
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version:  ==> libmagic: stable 5.45 (bottled)
LibreOffice version:  ==> libreoffice: 7.6.4

**Additional context**
![DA-1p](https://github.com/Unstructured-IO/unstructured/assets/43506685/1d996f25-351b-406d-a7e2-9a03fccf5827)
![DA-1p](https://github.com/Unstructured-IO/unstructured/assets/43506685/93cc5ddd-8560-4e50-b402-a1a217421efe)

**Comment by MthwRobinson** [comment] 2024-05-22 13:01
@christinestraub - Would your recent reading order updates have fixed this?

**Comment by christinestraub** [comment] 2024-05-22 17:41
I think so, I could not reproduce this bug in `main` branch with `unstructured-inference==0.7.32`. 
cc: @Coniferish @MthwRobinson

**Comment by MthwRobinson** [comment] 2024-05-22 17:42
Thanks @christinestraub ! Let's close this out then and we can reopen if it recurs.

**Closed by MthwRobinson** 2024-05-22 17:42 UTC
Labels: bug
