### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\41219\\AppData\\Local\\Temp\\tmp_1nbqb8c'

### ISSUE THREAD

**Issue by jjwwno** [Unstructured-IO/unstructured#3417] opened 2024-07-18 01:06 UTC
When I run the code：
from unstructured.partition.pdf import partition_pdf
elements = partition_pdf("test_14.pdf")
there is an error：Traceback (most recent call last):
  File "D:\py_solver\table_task\pdf_jiexi.py", line 4, in <module>
    elements = partition_pdf("test_14.pdf")
  File "d:\envs\table\lib\site-packages\unstructured\documents\elements.py", line 593, in wrapper
    elements = func(*args, **kwargs)
  File "d:\envs\table\lib\site-packages\unstructured\file_utils\filetype.py", line 626, in wrapper
    elements = func(*args, **kwargs)
  File "d:\envs\table\lib\site-packages\unstructured\file_utils\filetype.py", line 582, in wrapper
    elements = func(*args, **kwargs)
  File "d:\envs\table\lib\site-packages\unstructured\chunking\dispatch.py", line 74, in wrapper
    elements = func(*args, **kwargs)
  File "d:\envs\table\lib\site-packages\unstructured\partition\pdf.py", line 202, in partition_pdf
    return partition_pdf_or_image(
  File "d:\envs\table\lib\site-packages\unstructured\partition\pdf.py", line 341, in partition_pdf_or_image
    out_elements = _process_uncategorized_text_elements(elements)
  File "d:\envs\table\lib\site-packages\unstructured\partition\pdf.py", line 920, in _process_uncategorized_text_elements
    new_el = element_from_text(cast(Text, el).text)
  File "d:\envs\table\lib\site-packages\unstructured\partition\text.py", line 294, in element_from_text
    elif is_possible_narrative_text(text):
  File "d:\envs\table\lib\site-packages\unstructured\partition\text_type.py", line 80, in is_possible_narrative_text
    if exceeds_cap_ratio(text, threshold=cap_threshold):
  File "d:\envs\table\lib\site-packages\unstructured\partition\text_type.py", line 276, in exceeds_cap_ratio
    if sentence_count(text, 3) > 1:
  File "d:\envs\table\lib\site-packages\unstructured\partition\text_type.py", line 225, in sentence_count
    sentences = sent_tokenize(text)
  File "d:\envs\table\lib\site-packages\unstructured\nlp\tokenize.py", line 136, in sent_tokenize
    _download_nltk_packages_if_not_present()
  File "d:\envs\table\lib\site-packages\unstructured\nlp\tokenize.py", line 130, in _download_nltk_packages_if_not_present
    download_nltk_packages()
  File "d:\envs\table\lib\site-packages\unstructured\nlp\tokenize.py", line 88, in download_nltk_packages
    urllib.request.urlretrieve(NLTK_DATA_URL, tgz_file)
  File "d:\envs\table\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\41219\\AppData\\Local\\Temp\\tmp_1nbqb8c'

**Comment by scanny** [comment] 2024-07-18 18:02
Duplicate of #3390. @jjwwno try solution mentioned in that issue :)

**Closed by scanny** 2024-07-18 18:02 UTC
Labels: bug
