### ISSUE TITLE
feat/consolidate 'extra' dependency tests into a single CI run

### ISSUE THREAD

**Issue by newelh** [Unstructured-IO/unstructured#1159] opened 2023-08-19 11:26 UTC
**Is your feature request related to a problem? Please describe.**
Continuation of #747, the extras in the CI run are installed using a matrix which spins up 8 CI runs, an unfriendly amount of additional checks for a developer to visualize. Additionally, the OS level dependencies likely are not all needed. 

**Describe the solution you'd like**
Simplify the CI job to use a single runner for verifying the installation of each extra, also verify and use only the needed OS level dependencies. 

**Describe alternatives you've considered**
NA

**Additional context**
https://github.com/Unstructured-IO/unstructured/pull/1137#issuecomment-1684562784

**Comment by orlandounstructured** [comment] 2024-02-09 17:08
Awaiting eng update prior to closing

**Comment by orlandounstructured** [comment] 2024-02-09 17:13
Closing because longer than 180 days;
reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-09 17:13 UTC
Labels: enhancement, github_actions
