### ISSUE TITLE
UnicodeDecodeError in logger.info during the execution of partition_doc

### ISSUE THREAD

**Issue by MinnyKuan** [Unstructured-IO/unstructured#2449] opened 2024-01-24 02:10 UTC
hi,
I'm using version 0.11.8.
I use the following code to execute partition_doc :
```

from unstructured.partition.doc import partition_doc

filename = ""D:\\Testcase\\test.doc""
elements = partition_doc(filename=filename)

```

However, I encountered a UnicodeDecodeError occurring while executing convert_office_doc in ` logger.info(output.decode().strip())`
The error message is as follows:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 38: invalid start byte`

**Comment by MthwRobinson** [comment] 2024-01-24 13:30
@MinnyKuan - Any chance you can share the file that causes the error?

**Comment by MinnyKuan** [comment] 2024-01-25 01:25
Sure, because I cannot upload a doc file here, I used a compressed file.
This is a compressed file of a doc document:
[test.zip](https://github.com/Unstructured-IO/unstructured/files/14045576/test.zip)

**Comment by MthwRobinson** [comment] 2024-01-25 13:59
Thanks @MinnyKuan ! We'll look into this as soon as we can

**Comment by MthwRobinson** [comment] 2024-02-06 18:41
Hi @MinnyKuan - I was able to process the example doc using `partition_doc` on a Mac. Are you able to try this on Mac or Linux? From your example code it looks like you're on Windows.

**Comment by MinnyKuan** [comment] 2024-02-23 06:51
I tried to test in a Linux environment. 
The doc file shows the following error message, but the docx file does not.
`FileNotFoundError                         Traceback (most recent call last)`
![image](https://github.com/Unstructured-IO/unstructured/assets/74747729/bd7c79fa-2f7e-43d3-b67c-f0f959aaa236)


I also tried using the UnstructuredFileLoader method, but the result was the same.
I am currently still searching for a solution.

**Comment by srjchauhan** [comment] 2024-04-20 07:52
@MinnyKuan is this still a issue for you? I was able to process the example doc using `partition_doc` on my linux

**Comment by MinnyKuan** [comment] 2024-04-22 05:52
@scanny 
Yes, but currently I am converting the doc files to docx format locally before reading them. This allows me to continue using them.

**Comment by scanny** [comment] 2024-04-22 17:40
@MinnyKuan A couple things:
1. If you have already converted a document from `.doc` to `.docx`, you will need to call `partition_docx(...)` rather than `partition_doc(...)`.
2. Please post a minimum-reproducible-example that produces this problem in your environment: https://stackoverflow.com/help/minimal-reproducible-example
3. Post the entire stack trace you receive, not just the error message on the last line. This will allow us to pinpoint where the error is occuring.

If you can provide those I'll take a look :)

**Comment by scanny** [comment] 2024-04-27 00:25
Closing as cannot reproduce, assumed resolved.

**Closed by scanny** 2024-04-27 00:25 UTC
Labels: bug, docx
