### ISSUE TITLE
bug/text extraction is not great for attached PDF

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#845] opened 2023-06-29 01:51 UTC
**Describe the bug**
`partition()` has issues extracting clean text from various places in the attached PDF.
[CRPT-117hrpt397.pdf](https://github.com/Unstructured-IO/unstructured/files/11901233/CRPT-117hrpt397.pdf)

**To Reproduce**
run `partition()` against the PDF.

**Comment by SimranJha2408** [comment] 2023-12-18 05:36
is this resolved?

**Comment by orlandounstructured** [comment] 2024-02-08 23:20
Closing because longer than 180 days; reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-08 23:20 UTC
Labels: bug
