### ISSUE TITLE
Add support for enumerated lists in the `ListItem` detection logic

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#712] opened 2023-06-09 19:29 UTC
The goal of this issue is to update the `ListItem` detection logic to include enumerates lists with formats such as `(a)`, `(1)` and `(i)`. Currently we only detect unicode bullet characters.

**Comment by cragwolfe** [comment] 2023-06-11 22:01
Are there specific files that would be good to use as test cases?

**Comment by SimranJha2408** [comment] 2023-12-18 05:33
is this done?

**Comment by orlandounstructured** [comment] 2024-02-08 22:30
Closing because longer than 180 days; reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-08 22:30 UTC
