### ISSUE TITLE
bug/add_pytesseract_bbox_to_elements: not enough values to unpack

### ISSUE THREAD

**Issue by awalker4** [Unstructured-IO/unstructured#1318] opened 2023-09-06 20:28 UTC
**Describe the bug**
The hosted api hit the following error. We don't have a reproducer.

![Screenshot 2023-09-06 at 4 25 33 PM](https://github.com/Unstructured-IO/unstructured/assets/3846783/30c64986-be72-4cbc-8190-dd7eca35101b)

**Comment by chostyouwang** [comment] 2023-09-07 06:44
I've also encountered this error, have you resolved it?

**Comment by Coniferish** [comment] 2023-09-13 20:27
@chostyouwang, can you provide the file that created this error?

**Comment by MthwRobinson** [comment] 2024-05-10 12:44
Closing since we don't have an example to reproduce. If there's an example to reproduce this error, feel free to reopen. API has also developed significantly since the issue was opened, so likely this isn't an issue anymore.

**Closed by MthwRobinson** 2024-05-10 12:44 UTC
Labels: bug
