### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 

### ISSUE THREAD

**Issue by yufengaotianya** [Unstructured-IO/unstructured#3390] opened 2024-07-12 02:44 UTC
Problem description The system is Windows 11. When reading a txt document, PermissionError: [Errno 13] Permission denied: appears. The code is as follows:
```python
from unstructured.partition.auto import partition
partition("data_input\cureus\cureus-0015-00000040274.txt")
```
The problem code is located as follows:
```python
tokenize.py
with tempfile.NamedTemporaryFile() as tmp_file:
    tgz_file = tmp_file.name
urllib.request.urlretrieve(NLTK_DATA_URL, tgz_file)
```

I tested the following usage and it is also incorrect, and the same problem occurs;
```python
with tempfile.NamedTemporaryFile() as tmp_file:
    tfp = open(tmp_file.name, 'wb')
```
After checking the document, I found that the following code is normal on the linux system, but not supported on the windows system. So how to use it correctly on the windwos system partition("data_input\cureus\cureus-0015-00000040274.txt")

**Comment by scanny** [comment] 2024-07-12 22:59
@yufengaotianya please provide a full stack trace with line numbers so we can see where the problem is occurring.

Also, if you want us to understand the text please translate it to English for us :) I adjusted this one using Google Translate: https://translate.google.com/?sl=auto&tl=en&op=translate

@Coniferish probably something for you to look at while you're in there on the `txt` partitioner. I think what we're going to want to do is use `with tempfile.TemporaryDirectory() as tmpdir:` rather than `NamedTemporaryFile` which has known problems under Windows.

**Comment by Seanmjeong** [comment] 2024-07-15 04:21
[errno13.txt](https://github.com/user-attachments/files/16230022/errno13.txt)
Hi, I've recently ran into this issue as well. 

I've attached the trace. Hopefully it will help.

**Comment by scanny** [comment] 2024-07-15 05:11
Okay, thanks for this @seanmj :)

I think I've found the problem. Should be pushing the fix tomorrow some time.

In the meantime if you revert to v0.14.9 that should avoid this this problem for the time being. Let us know how you go :)

**Comment by ecarpentieri** [comment] 2024-07-15 07:29
Hi, 
I have the same problem when trying to read a docx!

I will try the last proposed solution of downgrading to v0.14.9

**Comment by ecarpentieri** [comment] 2024-07-15 08:10
> ```shell
> pip install -U unstructured==0.14.9
> ```

this solution works! ty

**Comment by hamitguner** [comment] 2024-07-17 12:44
> ```shell
> $ pip install -U unstructured==0.14.9
> ```

It worked for me too.

**Comment by Coniferish** [comment] 2024-07-26 19:20
@scanny, can you confirm and/or link the PR that addressed this issue and close this if appropraite?

> Okay, thanks for this @seanmj :)
> 
> I think I've found the problem. Should be pushing the fix tomorrow some time.
> 
> In the meantime if you revert to v0.14.9 that should avoid this problem for the time being. Let us know how you go :)
> 
> Something roughly like this should do the trick:
> 
> ```shell
> $ pip install -U unstructured==0.14.9
> ```

**Comment by scanny** [comment] 2024-07-26 21:58
Fixed by #3395. Installing `unstructured=0.15.0` or later will get that fix :)

**Closed by scanny** 2024-07-26 21:58 UTC
Labels: bug, txt

**Comment by akhilkapil** [comment] 2024-12-10 09:58
Hi @scanny, facing this similar issue again. Unstructured version is 0.16.5.

here's the trace:

`File "/usr/local/lib/python3.10/site-packages/unstructured/nlp/tokenize.py", line 86, in download_nltk_packagesn    urllib.request.urlretrieve(NLTK_DATA_URL, tgz_file_path)n  File "/usr/local/lib/python3.10/urllib/request.py", line 241, in urlretrieven    with contextlib.closing(urlopen(url, data)) as fp:n  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopenn    return opener.open(url, data, timeout)n  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in openn    response = meth(req, response)n  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_responsen    response = self.parent.error(n  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in errorn    return self._call_chain(*args)n  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chainn    result = func(*args)n  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_defaultn    raise HTTPError(req.full_url, code, msg, hdrs, fp)nurllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by scanny** [comment] 2024-12-10 17:14
Track on #3795
