### ISSUE TITLE
bug: Package not found error for PPTX

### ISSUE THREAD

**Issue by qued** [Unstructured-IO/unstructured#1773] opened 2023-10-17 14:54 UTC
Some PPTX files are generating `pptx.exc.PackageNotFoundError: Package not found at '<filename>.pptx'`.

"Package" here isn't referring to a Python package, this error is usually related to a file not being found or being of the wrong format.

**Comment by scanny** [comment] 2023-10-17 23:09
"Package" in this context means an "Open Packaging Convention (OPC)" package, a zip archive complying with that packaging standard having elements like `ppt/presentation.xml` and so forth.

This error indicates either no file exists at that path or the file that does exist is not a zip archive.

The latter can be confirmed with `unzip -l {path}/{filename}.pptx` on MacOS or Linux which would normally produce output like:

```bash
$ unzip -l prs-add-slide.pptx
Archive:  prs-add-slide.pptx
  Length      Date    Time    Name
---------  ---------- -----   ----
     1925  01-01-1980 00:00   [Content_Types].xml
      738  01-01-1980 00:00   _rels/.rels
      311  01-01-1980 00:00   ppt/slides/_rels/slide1.xml.rels
     1138  01-01-1980 00:00   ppt/_rels/presentation.xml.rels
     3228  01-01-1980 00:00   ppt/presentation.xml
      757  01-01-1980 00:00   ppt/slides/slide1.xml
   ...
      651  01-01-1980 00:00   ppt/presProps.xml
     1213  01-01-1980 00:00   docProps/app.xml
      788  01-01-1980 00:00   docProps/core.xml
     9395  01-01-1980 00:00   ppt/printerSettings/printerSettings1.bin
---------                     -------
    50574                     20 files
 ```

**Comment by badGarnet** [comment] 2023-10-20 18:05
@qued is there a file we can test or a code snippet we can start working with? Sounds like sometimes there will just be no such component in the input file and we just need to put guardrails in the code to anticipate this kind of exception?

**Comment by scanny** [comment] 2023-10-20 18:40
Just brainstorming, there are a couple of scenarios I could imagine that might give rise to this:

1. PowerPoint (and Word) create a "quick-save" working version of a file when it is open. So opening `foo.pptx` adds a `~foo.pptx` in the same directory. I'm not sure what format these are but they will not open with `python-pptx`. PowerPoint may recognize them as a possible recovery option, I'd have to check that, but in any case they are not valid PPTX files as they are. These can be left around if PowerPoint or Windows crashes while working on a presentation and can be left on the filesystem.
2. The file _was_ a PPTX at some point but it got corrupted or truncated or something and now would not load with PowerPoint (or `python-pptx`). This can definitely happen; probably not common but in a large collection of files it will happen every so often.
3. The file is the result of a conversion, I expect from an old `.ppt` format (pre-PowerPoint 2007) and the conversion didn't go well but the partial or perhaps empty result still got written to the output file we created (like `foo.ppt` is converted into `foo.pptx`). The LibreOffice conversion process uses an actual running instance of the LibreOffice client application as far as I can tell and it could be it gets unstable after a certain number of conversions (it seems to when I use it for tests, I need to restart LibreOffice when it gets painfully slow).
4. I could imagine an input file gets mis-identified as .ppt by libmagic or something and then the conversion fails but still produces an output file.

I don't have actual evidence of any of these, but if we don't have a concrete example such speculation might be all we have to go on.

**Comment by scanny** [comment] 2023-11-17 00:39
@qued is this still a problem? I'm going to close it for now since it's not actionable, but feel free to reopen if it's still happening and I'll be happy to work out what's causing it :)

**Closed by scanny** 2023-11-17 00:39 UTC
Labels: bug, pptx
