### ISSUE TITLE
bug/PDFMiner `KeyError: 'N'` when `partition.auto` particular PDFs

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured#2070] opened 2023-11-14 10:34 UTC
**Describe the bug**
There is a `KeyError: 'N'` coming from `pdfminer/pdftypes.py` when parsing the attached PDFs.
Backtracking, the call comes from `pdfminer/pdfinterp.py` related to the class `PDFColorSpace`:
```
if name == "ICCBased" and isinstance(spec, list) and 2 <= len(spec):
    return PDFColorSpace(name, stream_value(spec[1])["N"])
```

**To Reproduce**
```
curl -q -X POST https://api.unstructured.io/general/v0/general -H 'unstructured-api-key: XXXXXXXXX ' -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F hi_res_model_name=chipperv2 -F strategy=hi_res -F files=@License_application_700028_0-4.pdf -o error.json
```

**Expected behavior**
`partition_pdf` normal behaviour successfully parsing PDF.

**Environment Info**
```
OS version:  macOS-13.4.1-arm64-arm-64bit
Python version:  3.9.18
unstructured version:  0.10.28
unstructured-inference version:  0.7.10
pytesseract version:  0.3.10
Torch version:  2.0.1
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version:  ==> libmagic: stable 5.45 (bottled)
LibreOffice version:  ==> libreoffice: 7.6.2
```

**Additional context**
The error is NOT particular of `chipperv2`. The bug is also there when the call is made with `yolox` as the `hi_res_model_name`.

So far, only the attached forms `License_application_700028_0-1.pdf` and `License_application_700028_0-4.pdf` present the erroneous behaviour.
[License_application_700028_0-1.pdf](https://github.com/Unstructured-IO/unstructured/files/13347591/License_application_700028_0-1.pdf)
[License_application_700028_0-4.pdf](https://github.com/Unstructured-IO/unstructured/files/13347592/License_application_700028_0-4.pdf)

**Comment by awalker4** [comment] 2023-11-14 15:33
Duplicate of #2059 , but good to have more reproducers!

**Comment by cragwolfe** [comment] 2023-11-14 17:51
Closing since is a dupe.

**Closed by cragwolfe** 2023-11-14 17:51 UTC
Labels: bug
