### ISSUE TITLE
bug/PIL library as a dependency requirement for PDF in Python v3

### ISSUE THREAD

**Issue by mlc-mlapis** [Unstructured-IO/unstructured#2456] opened 2024-01-25 04:38 UTC
The actual code https://github.com/Unstructured-IO/unstructured/blob/d8b3bdb919579dddba8bfc925e4b99ca807e3005/unstructured/partition/auto.py#L79 requires the PIL library that is not available in Python v3. Using the `unstructured` library always leads to the error message `ImportError: partition_pdf is not available. Install the pdf dependencies with pip install "unstructured[pdf]"`.
```
pdf_imports = ["pdf2image", "pdfminer", "PIL"]
if all(dependency_exists(dep) for dep in pdf_imports):
    from unstructured.partition.pdf import partition_pdf

    PARTITION_WITH_EXTRAS_MAP["pdf"] = partition_pdf
```

**Environment Info**
Python 3.10.5

**Comment by mlc-mlapis** [comment] 2024-03-11 11:52
Any reaction from the team?

**Comment by scanny** [comment] 2024-03-11 17:39
@mlc-mlapis Is this causing you a problem? The actual dependency is on `Pillow`, but that package presents itself as `PIL` in the Python module namespace, which is what `dependency_exists()` uses. Like when you install `Pillow` with `pip install pillow` you access it with `from PIL import Image`.

Closing this as not a bug, but if you're getting an error or something feel free to reopen and we'll investigate :)

**Closed by scanny** 2024-03-11 17:39 UTC
Labels: bug
