### ISSUE TITLE
bug/pytesseract-dependency-with-unstructured-pdf-option

### ISSUE THREAD

**Issue by SebastianWolfschmidtAA** [Unstructured-IO/unstructured#3526] opened 2024-08-15 13:50 UTC
**Describe the bug**
I am using a poetry project with unstructured. 
When I simply install unstructured, installing the dependency works fine. 

When I only want to use the pdf support, resolving the dependencies fails. This did not happen with version `0.15.1`.

**To Reproduce**

Dependency in the `pyproject.toml`:
`unstructured = {version= "0.15.3", extras=['pdf']}`

This gives the error:
"Because unstructured[pdf] (0.15.3) depends on pytesseract (>=0.3.12) which doesn't match any versions, unstructured is forbidden.
So, because <the project> depends on unstructured[pdf] (0.15.3), version solving failed."
This also does not work when manually adding the dependency `unstructured-pytesseract = 0.3.12`.
When simply using `unstructured = "0.15.3"`, dependencies are resolved correctly.

**Expected behavior**
Dependency should resolve correctly also when only wanting support for pdfs.

**Comment by isaackogan** [comment] 2024-08-15 15:10
This is fixed in 0.15.4 which is...not released on PyPi yet but is available in releases1

**Comment by cbornet** [comment] 2024-08-16 11:20
I think 0.15.4 couldn't be published to pypi because it was using github and not pypi for pytesseract.
So the fixed version will probably be 0.15.5+.

**Comment by cbornet** [comment] 2024-08-16 11:22
Duplicate of https://github.com/Unstructured-IO/unstructured/issues/3521

**Closed** 2024-08-16 16:40 UTC
Labels: bug
