### ISSUE TITLE
html split why image info missing

### ISSUE THREAD

**Issue by JYYzhengjunjie** [Unstructured-IO/unstructured#3413] opened 2024-07-17 09:38 UTC
Why is the image information lost when the HTML file is split? I understand that I don't want to perform OCR on the image in HTML, but I want to keep the CDN address of the image in HTML. However, the CDN address of the image is directly discarded.

**Comment by scanny** [comment] 2024-12-18 08:00
Closing as duplicate of #3606.

**Closed by scanny** 2024-12-18 08:00 UTC
