### ISSUE TITLE
bug/macos-arm64-and-lxml-import-error

### ISSUE THREAD

**Issue by liamvdv** [Unstructured-IO/unstructured#1707] opened 2023-10-11 09:02 UTC
**Describe the bug**
Cannot use unstructured on MacOS M2 Pro because `from unstructured.partition.html import partition_html` throws
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liamvdv/src/github.com/REDACT/.venv/lib/python3.9/site-packages/unstructured/partition/html.py", line 7, in <module>
    from unstructured.documents.html import HTMLDocument
  File "/Users/liamvdv/src/github.com/REDACT/.venv/lib/python3.9/site-packages/unstructured/documents/html.py", line 11, in <module>
    from lxml import etree
ImportError: dlopen(/Users/liamvdv/src/github.com/REDACT/.venv/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '___cyg_profile_func_enter'
```

**To Reproduce**
```
brew install python@3.9
python3.9 -m venv .venv
source .venv/bin/activate
python --version # should show 3.9 now
which python # should be .../.venv/bin/....
pip install unstructured
python
# in interactive shell
from unstructured.partition.html import partition_html
```
on my machine throws 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liamvdv/src/github.com/REDACT/.venv/lib/python3.9/site-packages/unstructured/partition/html.py", line 7, in <module>
    from unstructured.documents.html import HTMLDocument
  File "/Users/liamvdv/src/github.com/REDACT/.venv/lib/python3.9/site-packages/unstructured/documents/html.py", line 11, in <module>
    from lxml import etree
ImportError: dlopen(/Users/liamvdv/src/github.com/REDACT/.venv/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '___cyg_profile_func_enter'
```
**Expected behavior**
Normal import to then parse HTML/XML files.

**Screenshots**
<img width="1185" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/62619917/9d77808e-e24c-4e63-8403-703e8e20788e">

**Environment Info**
```
/Users/liamvdv/src/github.com/REDACT/collect.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
OS version:  macOS-13.4.1-arm64-arm-64bit
Python version:  3.9.18
unstructured version:  0.10.19
unstructured-inference is not installed
pytesseract is not installed
Torch is not installed
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version: file-5.41
magic file from /usr/share/file/magic
Traceback (most recent call last):
  File "/Users/liamvdv/src/github.com/REDACT/collect.py", line 242, in <module>
    main()
  File "/Users/liamvdv/src/github.com/REDACT/collect.py", line 234, in main
    libreoffice_version = get_libreoffice_version()
  File "/Users/liamvdv/src/github.com/REDACT/collect.py", line 163, in get_libreoffice_version
    result = subprocess.run(
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'libreoffice'
```
**Additional context**
I'm on a Mac M2 Pro with macOS Version 13.4.1.

Thank you for your help.

**Comment by badGarnet** [comment] 2023-10-20 20:26
Hi @liamvdv sorry for a late response; we are tracking this and reviewing the problem. Will keep this thread updated.

**Comment by MikeRecognex** [comment] 2024-04-14 08:53
This thread hasn't been updated.  Is it fixed?

**Comment by zihaolam** [comment] 2024-04-16 13:54
having same issue too

**Comment by scanny** [comment] 2024-04-28 01:25
After getting an Apple Silicon Mac I was finally able to reproduce this error.

I believe the problem is that `arm64` wheels are not available for the latest versions of `lxml`. The solution that worked for me is the following:
```bash
$ pip install lxml==4.9.2
```
The later versions of `lxml` have "universal" macOS wheels and for some reason those don't seem to work.

**Comment by MthwRobinson** [comment] 2024-05-16 14:27
Closing this issue. You can try @scanny 's suggestion from above if you run into this issue.

**Closed by MthwRobinson** 2024-05-16 14:27 UTC
Labels: bug, packaging
