### ISSUE TITLE
(PDF) The output of the model `yolox` is different when used via api

### ISSUE THREAD

**Issue by piegu** [Unstructured-IO/unstructured#2290] opened 2023-12-18 17:04 UTC
**Describe the bug**

The output of the model `yolox` is different when used via api.
I did the test with a PDF I created using `LibreOffice Writer >> Export to PDF` : [test_with_yolox_text_por.pdf](https://github.com/piegu/language-models/blob/master/docs/tests/test_with_yolox_text_por.pdf)

Characteristics of this PDF:
- written in Portuguese
- a table created inside the LibreOffice Writer with the menu Table

JSON files as outputs (see link to notebook in the paragraph "To Reproduce"):
- from `local yolox` (use of `partition_pdf`): [test_with_yolox_text_por_pdf_local_yolox.json](https://github.com/piegu/language-models/blob/master/docs/tests/test_with_yolox_text_por_pdf_local_yolox.json)
- from `yolox via api` (use of `partition_via_api`): [test_with_yolox_text_por_pdf_api_yolox.json](https://github.com/piegu/language-models/blob/master/docs/tests/test_with_yolox_text_por_pdf_api_yolox.json)

**I expected to get exactly the same json file but not.** 

In particular, I did notice the following points:
- **language**
  - `yolox via api` does not use the information about language given in the parameter `languages`: in its json file, you can verify that each element gets `"languages": ["eng"]` even if I passed `"languages": ["por"]`.
  - On the contrary, `local yolox` wrote in the json file for each element `"languages": ["por"]`, which is the expected output.
- **table**
  - `yolox via api` makes a very bad work on this very easy table from PDF when `local yolox` gets it perfectly.
  - more, with `yolox via api`, the value of the keys `"text_as_html"` and `"text"` are different (out of the balises html of course). I copied/pasted below the 2 values. Thus, we can see that in the value of the key `"text_as_html"`, we find for example "lgmewe" which is not in the value of the key `"text"` (and which is not in the table of the PDF).
    - `"text_as_html"`: <table><thead><th>i</th><th>wo</th><th>[ |</th><th></th><th>lgmewe</th></thead><tr><td>2 |</td><td></td><td>leswss |</td><td></td><td>|</td></tr><tr><td></td><td></td><td>R</td><td>R</td><td>Y</td></tr><tr><td>TOTAL</td><td>288.284.696,00</td><td>|88.876,98</td><td>-</td><td>]1.065.974,00</td></tr></table>
    - `"text"`: Produtos Q1 Q2 p1 p2 p3 p4 1.899,00 288282.797,00 88.876,98 TOTAL 288.284.696,00 88.876,98 Q3 Q4 877.987,00 187.987,00 1.065.974,00
  - from this [issue #2271 ](https://github.com/Unstructured-IO/unstructured/issues/2271), different values between the keys `"text_as_html"` and `"text"` happens as well with `local yolox`

**To Reproduce**

Notebook to get JSON from this PDF both with  `local yolox` and  `yolox via api`: [Unstructured_PDF_to_json_with_yolox_local_vs_api.ipynb](https://github.com/piegu/language-models/blob/master/docs/tests/Unstructured_PDF_to_json_with_yolox_local_vs_api.ipynb)

**Expected behavior**

I expected to get exactly the same json files when using `local yolox` or  `yolox via api`. Unfortunately, it is not the case.

**Environment Info**
- unstructured 0.11.5
- unstructured-inference 0.7.19
- Google Colab

**Additional context**

(see the [issue #2291](https://github.com/Unstructured-IO/unstructured/issues/2291)) When I use `chipper via api,` I meet as well the same error with the key `languages` in the JSON that stays `["eng"]` even if I did setup `languages=["por"]` in the `partition_via_api` function.

**Comment by MthwRobinson** [comment] 2024-08-26 14:26
Closing because this is expected behavior. The YOLOX model available through the Serverless API is more accurate that the version available in open source.

**Closed by MthwRobinson** 2024-08-26 14:26 UTC
Labels: bug
