### ISSUE TITLE
Add support for processing `.mbox` files

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#755] opened 2023-06-15 13:21 UTC
The goal of this issue is to add support for processing `.mbox` files so that users can process an entire mailbox instead each `.eml` file individually.

**Comment by kafkasl** [comment] 2023-06-23 16:19
any suggestion on how to implement this? I've been using other people's repository to do the conversion before using this repo. They were not too reliable so I was not going to test this one https://github.com/noelmartinon/mboxzilla.git.

**Comment by SimranJha2408** [comment] 2023-12-18 05:34
did we implement this?

**Comment by orlandounstructured** [comment] 2024-02-08 22:43
Closing because longer than 180 days; reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-08 22:43 UTC
