### ISSUE TITLE
Extract text from images and maps embedded in documents

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#1019] opened 2023-08-01 19:11 UTC
Currently, the partition functions do not process images and maps that are embedded in documents. The goal of this issue is to allow users to optionally extract text from images and maps.

**Comment by orlandounstructured** [comment] 2024-02-08 23:45
Closing because longer than 180 days;
reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-08 23:45 UTC
Labels: enhancement
