### ISSUE TITLE
bug/Chunking is splitting some element randomly

### ISSUE THREAD

**Issue by vikasr111** [Unstructured-IO/unstructured#1856] opened 2023-10-24 02:00 UTC
**Describe the bug**
I am trying to use chunking by title on a simple PDF document using the code snippet from the documentation. I am noticing that it's splitting some **`NarrativeText`** element texts and shows the texts in different chunks. In fact it's even splitting some words in the middle and shows the characters in different chunks. This is quite unexpected as the documentation says that it does not split an element.

**To Reproduce**
Here's my code snippet which I am using for the attached file.
```
file_path = "/content/meta-report-1.pdf"
elements = partition(file_path)

chunks = chunk_by_title(elements)

for chunk in chunks:
    print(chunk)
    print("\n\n" + "-"*80)
```

**Expected behavior**
It should return chunks where each full element goes into one chunk. But my output shoes single element texts getting split into two chunks. 

**Example**
Here's the input document [meta-report-1.pdf](https://github.com/Unstructured-IO/unstructured/files/13103429/meta-report-1.pdf)

Look at the example of two chunks produced from the input document using the code above. Notice the end of first chunk and beginning of second chunk.

```
--------------------------------------------------------------------------------
Family daily active people (DAP) – DAP was 3.07 billion on average for June 2023, an increase of 7% year-over- year. Family monthly active people (MAP) – MAP was 3.88 billion as of June 30, 2023, an increase of 6% year-over- year. Facebook daily active users (DAUs) – DAUs were 2.06 billion on average for June 2023, an increase of 5% year- over-year. Facebook monthly active users (MAUs) – MAUs were 3.03 billion as of June 30, 2023, an increase of 3% year- over-year. Ad impressions and price per a


--------------------------------------------------------------------------------
d – In the second quarter of 2023, ad impressions delivered across our Family of Apps increased by 34% year-over-year and the average price per ad decreased by 16% year-over-year.
```

**Comment by badGarnet** [comment] 2023-10-25 15:24
Hi @vikasr111 thanks for reporting this issue. We are tracking it and will review this soon.

**Comment by badGarnet** [comment] 2023-10-25 15:38
@vikasr111 could you please let us know what version produced this error? Have you tried to upgrade `unstructured`? And could you also check the contents in the elements? It may be that the element detection is segmenting the contents too aggressively. cc @benjats07

**Comment by vikasr111** [comment] 2023-10-25 22:35
@badGarnet Thanks for picking it up.  I am using the latest version of Unstructured in the Colab using `pip install "unstructured[all-docs]"`. I have added the actual file I am using and the code in the bug report above. The elements are getting segmented fine, the problem appears in chunking.

For better reference I am pasting the elements extracted from the file as it's a one page file:

```
(unstructured.documents.elements.Title,
 'Meta Reports Second Quarter 2023 Results')
(unstructured.documents.elements.NarrativeText,
 'MENLO PARK, Calif. – July 26, 2023 – Meta Platforms, Inc. (Nasdaq: META) today reported financial results for the quarter ended June 30, 2023.')
(unstructured.documents.elements.NarrativeText,
 '"We had a good quarter. We continue to see strong engagement across our apps and we have the most exciting roadmap I\'ve seen in a while with Llama 2, Threads, Reels, new AI products in the pipeline, and the launch of Quest 3 this fall," said Mark Zuckerberg, Meta founder and CEO.')
(unstructured.documents.elements.Title,
 'Second Quarter 2023 Financial Highlights')
(unstructured.documents.elements.Text, 'Three Months Ended June 30,')
(unstructured.documents.elements.Title,
 'In millions, except percentages and per share amounts')
(unstructured.documents.elements.Text, '2023')
(unstructured.documents.elements.Text, '2022')
(unstructured.documents.elements.Title, '% Change')
(unstructured.documents.elements.Title, 'Revenue')
(unstructured.documents.elements.Text, '$')
(unstructured.documents.elements.Text, '31,999 $')
(unstructured.documents.elements.Text, '28,822')
(unstructured.documents.elements.Text, '11%')
(unstructured.documents.elements.Title, 'Costs and expenses')
(unstructured.documents.elements.Text, '22,607')
(unstructured.documents.elements.Text, '20,464')
(unstructured.documents.elements.Text, '10%')
(unstructured.documents.elements.Title, 'Income from operations')
(unstructured.documents.elements.Text, '$')
(unstructured.documents.elements.Text, '9,392 $')
(unstructured.documents.elements.Text, '8,358')
(unstructured.documents.elements.Text, '12%')
(unstructured.documents.elements.NarrativeText, 'Operating margin')
(unstructured.documents.elements.Text, '29 %')
(unstructured.documents.elements.Text, '29 %')
(unstructured.documents.elements.Title, 'Provision for income taxes')
(unstructured.documents.elements.Text, '$')
(unstructured.documents.elements.Text, '1,505 $')
(unstructured.documents.elements.Text, '1,499')
(unstructured.documents.elements.Text, '—%')
(unstructured.documents.elements.Title, 'Effective tax rate')
(unstructured.documents.elements.Text, '16 %')
(unstructured.documents.elements.Text, '18 %')
(unstructured.documents.elements.Title, 'Net income')
(unstructured.documents.elements.Text, '$')
(unstructured.documents.elements.Text, '7,788 $')
(unstructured.documents.elements.Text, '6,687')
(unstructured.documents.elements.Text, '16%')
(unstructured.documents.elements.NarrativeText,
 'Diluted earnings per share (EPS)')
(unstructured.documents.elements.Text, '$')
(unstructured.documents.elements.Text, '2.98 $')
(unstructured.documents.elements.Text, '2.46')
(unstructured.documents.elements.Text, '21%')
(unstructured.documents.elements.Title,
 'Second Quarter 2023 Operational and Other Financial Highlights')
(unstructured.documents.elements.NarrativeText,
 'Family daily active people (DAP) – DAP was 3.07 billion on average for June 2023, an increase of 7% year-over- year. Family monthly active people (MAP) – MAP was 3.88 billion as of June 30, 2023, an increase of 6% year-over- year. Facebook daily active users (DAUs) – DAUs were 2.06 billion on average for June 2023, an increase of 5% year- over-year. Facebook monthly active users (MAUs) – MAUs were 3.03 billion as of June 30, 2023, an increase of 3% year- over-year. Ad impressions and price per ad – In the second quarter of 2023, ad impressions delivered across our Family of Apps increased by 34% year-over-year and the average price per ad decreased by 16% year-over-year.')
(unstructured.documents.elements.ListItem,
 'Revenue – Revenue was $32.0 billion, an increase of 11% year-over-year, and an increase of 12% year-over-year on')
(unstructured.documents.elements.NarrativeText,
 'a constant currency basis. Costs and expenses – Total costs and expenses were $22.61 billion, an increase of 10% year-over-year. This includes accrued legal expenses of $1.87 billion and restructuring charges of $780 million in the second quarter of 2023. Capital expenditures – Capital expenditures, including principal payments on finance leases, were $6.35 billion for the second quarter of 2023. Share repurchases – We repurchased $793 million of our Class A common stock in the second quarter of 2023. As of June 30, 2023, we had $40.91 billion available and authorized for repurchases. Cash, cash equivalents, and marketable securities – Cash, cash equivalents, and marketable securities were $53.45 billion as of June 30, 2023. Free cash flow was $10.96 billion in the second quarter of 2023. Long-term debt – Long-term debt was $18.38 billion as of June 30, 2023.')
(unstructured.documents.elements.ListItem,
 '• Headcount – Headcount was 71,469 as of June 30, 2023, a decrease of 14% year-over-year. Approximately half of the employees impacted by the 2023 layoffs are included in our reported headcount as of June 30, 2023.')
(unstructured.documents.elements.Text, '1')
```

**Comment by vikasr111** [comment] 2023-10-27 12:50
@badGarnet @benjats07 Hope the details I shared helped. Please let me know if you need any other info that helps in identifying the problem.

**Comment by badGarnet** [comment] 2023-10-27 17:08
Hi @vikasr111 sorry for a late response. So I was able to reproduce the behavior. This splitting is actually due to the default value for `max_characters` (limiting how many characters a chunk can have) is set to 500: https://github.com/Unstructured-IO/unstructured/blob/f273a7cb83310d1e953605a47d55965448e716d7/unstructured/chunking/title.py#L63
This means that every 500 characters, even if inside an element, the chunking algorithm will split the text.

The intention of this max character to is for downstream applications to have a control on how much text can be inside a chunk. Sometimes maybe the embedding task or LLM task downstream do not work well or at all with text larger than certain sizes so this parameter can do that splitting. 

If you do not wish the algorithm to split we can set the `max_characters` to a large value like 100,000. 

I think what might be worth asking as follow up is:
- do we want to allow `max_characters` to be `None` to never split in element
- update documentation to explain it better.
cc @scanny who has been working on chunking recently.

**Comment by scanny** [comment] 2023-10-27 18:19
Hi @vikasr111, there are two chunking options that might be of interest here:

* `max_characters` (hard maximum size of chunk)
* `new_after_n_chars` (preferred maximum size of chunk)

The behaviors these produce are:
- As many sequential elements as will together fit within the preferred window are combined into a single chunk.
- A single element that exceeds the preferred size is isolated into its own chunk.
- When that single element also exceeds the hard chunk window, it is split mid-text.

By combining the two options you can express both a preferred or "usual" size and also a threshold for mid-text splitting.

For example in your case, you might choose: `(new_after_n_chars=500, max_characters=5000)`

Which would perhaps produce chunks that were mostly between 400-500 chars but allow an occasional large single element to produce a longer chunk without mid-text splitting.

If you are able to share more on what chunk characteristics suit your use case, that would help us with evolving the chunking behaviors and may also allow us to suggest something more that would help configure the current behaviors to suit.

In any case, let us know how you go with this :)

**Comment by scanny** [comment] 2023-11-17 00:59
Hi @vikasr111 just following up to see if there was anything else you needed on this. Closing it now as resolved, but feel free to reopen it if there's anything else we can do on it :)

**Closed by scanny** 2023-11-17 00:59 UTC
Labels: bug
