### ISSUE TITLE
bug/ingest: partition-by-api fails silently on bad status code

### ISSUE THREAD

**Issue by awalker4** [Unstructured-IO/unstructured#1195] opened 2023-08-24 15:27 UTC
**Describe the bug**
I ran the following command and forgot to pass an api key:
```
./unstructured/ingest/main.py local --partition-by-api --input-path example-docs --structured-output-dir ./output
...
...
2023-08-24 11:23:41,616 SpawnPoolWorker-2 INFO     Processing example-docs/english-and-korean.png
2023-08-24 11:23:41,616 SpawnPoolWorker-1 INFO     Processing example-docs/science-exploration-369p.pptx
2023-08-24 11:23:41,616 SpawnPoolWorker-2 DEBUG    Using remote partition (https://api.unstructured.io/general/v0/general)
2023-08-24 11:23:41,616 SpawnPoolWorker-1 DEBUG    Using remote partition (https://api.unstructured.io/general/v0/general)
2023-08-24 11:23:41,901 SpawnPoolWorker-2 INFO     Processing example-docs/fake-power-point.pptx
2023-08-24 11:23:41,901 SpawnPoolWorker-2 DEBUG    Using remote partition (https://api.unstructured.io/general/v0/general)
```

When the command finishes, no output dir was created. I confirmed that the response [here](https://github.com/Unstructured-IO/unstructured/blob/1524841cd96a160c69edb29caca1c42863b7800f/unstructured/ingest/interfaces.py#L238) was 401.

**Expected behavior**
I would expect the command to fail as soon as the first 401 is returned.

**Comment by rbiseck3** [comment] 2023-08-28 19:52
This gets into a broader design conversation about the ingest cli. Since each doc is processed in it's own process, _should_ the entire process break if one of them does? Given that the entire CLI run can include reading, partitioning and writing the content, we need to decide what the best approach is for handling errors in the middle of that process. 

Regarding this specific issue, we might just need to increase the logging around the api response code.

**Comment by orlandounstructured** [comment] 2024-02-09 18:54
Closing due to 180 days; reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-09 18:54 UTC
Labels: bug
