### ISSUE TITLE
feat/extracting-images

### ISSUE THREAD

**Issue by theZaX** [Unstructured-IO/unstructured#805] opened 2023-06-25 05:53 UTC
In my specific application, having the images in relation to the other segments of the partition would be very helpful. This effectively would allow me to use semantic search to locate relevant images inside of a document and use them intelligently. 

I'm not as worried about the text content of the images  -  I would likely run them through an image captioning service to know what the actual content of the image is.

**Describe the solution you'd like**
It would be great to have the images come back from the partition as some sort of segment, without any text content. I would somehow need to also get the images out of the document, so that could be either a base64 string in the json or some sort of indexing system where it uses reference ids and a second endpoint is used to extract the images from the document. 
This could also become more relevant / helpful as LLMs become multimodal. 

**Additional context**
I'm using a self hosted version of unstructured API, our service accepts docx, doc, pptx, ppt, pdf, txt, and web.

**Comment by MthwRobinson** [comment] 2023-06-27 13:29
Thanks @theZaX ! We'll take a look at this as soon as we can. We've had a few other users express interest in extracting images as well.

**Comment by hooman-bayer** [comment] 2023-08-14 19:14
hi @MthwRobinson any updates on this? Or whether you might wanna have this in your roadmap? I think given the latest state of [ML models](https://arxiv.org/abs/2212.10505), it is possible to make sense of images pretty nicely. Specially in ppt formats where a lot of content might be buried in images.

Thanks in advance

**Comment by cragwolfe** [comment] 2023-08-15 04:29
> **Describe the solution you'd like**
It would be great to have the images come back from the partition as some sort of segment, without any text content. I would somehow need to also get the images out of the document, so that could be either a base64 string in the json or some sort of indexing system where it uses reference ids and a second endpoint is used to extract the images from the document.

In the immediate term, would a partition kwarg such as `image_data=base64` make sense here?

**Comment by BenSpex** [comment] 2023-08-15 11:49
I would very much appreciate this feature as well. 

Another option could be to find captions, which might be easier in pdf than other documents. 
Eg. attach the caption if common key words like figure etc. are present right below the image.

**Comment by cragwolfe** [comment] 2023-08-15 16:54
@BenSpex , thanks for the reference to that GitHub repo.

With respect to captions, the default layout model currently does identify some `FigureCaption`s, e.g. in this [test fixture](https://github.com/Unstructured-IO/unstructured/blob/350bb1d/test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json#L1113).

However, it is clearly not identifying all of them, so that's one issue, and the extracted text may have some noise (another issue). With regard to the former, we plan on a layout model in the near future that may help be better with identification.

**Comment by BenSpex** [comment] 2023-08-15 20:18
@cragwolfe 
Ah good to know. 

For me, on [this](https://www.tandfonline.com/doi/epdf/10.1080/07060661.2023.2224776?needAccess=true&role=button) pdf it did not work. 

```json
{
    "type": "NarrativeText",
    "element_id": "c72b2f8025265db2be27143df6708037",
    "metadata": {
      "filename": "Crown gall development on cannabis Cannabis sativa L marijuana plants caused by Agrobacterium tumefaciens species complex.pdf",
      "filetype": "application/pdf",
      "page_number": 9
    },
    "text": "Fig. 4 PCR analysis for presence of Agrobacterium in cannabis tissue samples using primers iaaH-F2 and iaaH-R1. (a) Lane L = 1 kb Plus DNA ladder; lane 1 = root gall sample A; lane 2 = crown gall sample C; lane 3 = ATCC 15955 positive control; lane 4 = cannabis genotype WHR negative control; lane 5 = artificially inoculated gall using ATCC 15955 on genotype CPH; lane 6 = cannabis genotype CPH negative control; lane 7 = artificially inoculated gall using ATCC 15955 on genotype SWD; lane 8 = cannabis genotype SWD negative control. Red arrows indicate sequences that were identified as Agrobacterium using NCBI BLAST. (b) Lane L = 1 kb Plus DNA ladder; lane 1 = ATCC 15955 positive control; lane 2 = artificially inoculated gall using ATCC 15955 on genotype CPH; lanes 3\u20138 = galls on stems from 6 different cuttings of genotype PNK; lane 9 = artificially inoculated gall using ATCC 15955 on genotype SWD. (c) PCR analysis using primers iaaH- F10 and iaaH-R10. Lanes 1 and 2 = root gall sample A; lane 3 = crown gall sample C of genotype WHR; lanes 4 and 5 = ATCC 15955 positive control; lanes 6 and 7 = cannabis genotype WHR negative control; lanes 8 and 9 = artificially inoculated gall using ATCC 15955 on genotype CPH; lanes 10 and 11 = cannabis genotype CPH negative control; lanes 12 and 13 = artificially inoculated gall using ATCC 15955 on genotype SWD; and lanes 14 and 15 = cannabis genotype CPH negative control. The red arrows indicate the size of highly amplified bands between positive and negative samples."
  },
```

In this very small test set of 1, it did not work. Although `Fig.4`  should be quite descriptive. 

However the [online PDFigCapx](https://www.eecis.udel.edu/~compbio/PDFigCapX) did a pretty good job on the pdf. 
![image](https://github.com/Unstructured-IO/unstructured/assets/52712273/6c311fc3-8aa0-42bd-aab4-6457b226ae94)

It actually found all figures with captions: 
![image](https://github.com/Unstructured-IO/unstructured/assets/52712273/ca174c47-f5c0-4c09-9f07-4f0b49179ed8)


However the linked code is not really production worthy to be honest, and is taking a detour through html and chrome rendering to actually find the images and extract the captions. 

But overall the actual algorithm is rather simple and pretty much solely relies on the layout, which I think is probably cheaper to compute than anything content wise and at least for research publication style pdfs good enough. 
But it will most likely fail in most other contents. 

For our use case, the pure layout based option would be good enough. 
If you could point me in the right direction I would be happy to put some effort in and try to recreate the [PDFigCapX](https://github.com/pengyuanli/PDFigCapX/tree/main) algorithm with your processing pipeline.

**Comment by BenSpex** [comment] 2023-08-16 21:45
Quick Update, here is code snippet that works good enough for me, feel free to adjust it to your liking.
It extracts the tables and images with [pdfplumber](https://github.com/jsvine/pdfplumber) and then searches for the most likely text box extracted from [UnstructeredAPI](https://unstructured-io.github.io/unstructured/api.html) with `coordinates=true`

```python
import pdfplumber
import os
import json
tmp_path =  '/tmp_images'

COMMON_IMAGE_CAPTIONS = ['fig.', 'figure', 'fig', 'figs', 'figures','table', 'tables', 'pic', 'picture']
def extract_images(path, captions):
    #Extract images from pdf
    with (pdfplumber.open(path) as pdf):
        for i, page in enumerate(pdf.pages):
            for j, image in enumerate(page.images):
                page_height = page.height
                image_bbox = (image['x0'], page_height - image['y1'], image['x1'], page_height - image['y0'])
                #ensure that the image_bbox is within the page else crop the image_bbox
                if image_bbox[0] < 0:
                    image_bbox = (0, image_bbox[1], image_bbox[2], image_bbox[3])
                if image_bbox[1] < 0:
                    image_bbox = (image_bbox[0], 0, image_bbox[2], image_bbox[3])
                if image_bbox[2] > page.width:
                    image_bbox = (image_bbox[0], image_bbox[1], page.width, image_bbox[3])
                if image_bbox[3] > page.height:
                    image_bbox = (image_bbox[0], image_bbox[1], image_bbox[2], page.height)

                cropped_page = page.crop(image_bbox)
                image_obj = cropped_page.to_image(resolution=300, antialias=True)
                image_obj.save(os.path.join(tmp_path,f"Image_{i}-{j}.png"), format="PNG", optimize=True, quantize=False)
                caption_candidates = captions[i+1]
                caption_coords = []
                caption_texts = []
                for candidate in caption_candidates:
                    # check if any word of the COMMON_IMAGE_CAPTIONS is in the text
                    if any([word in candidate['text'][:30].lower() for word in COMMON_IMAGE_CAPTIONS]):
                        caption_coords.append(candidate['coordinates'])
                        caption_texts.append(candidate['text'])
                if not caption_coords:
                    print(f'No caption found for image {i}-{j}')
                    print()
                    continue
                else:
                    ranked_indices = rank_captions(image_bbox, caption_coords)
                    caption_text = caption_texts[ranked_indices[0]]
                    print(f'Image {i}-{j} is most likely to be captioned by this text: {caption_text}')
                    print()
            tables = page.find_tables({'vertical_strategy':'lines','horizontal_strategy':'lines'})

            for table_idx, table in enumerate(tables):
                # Get the bounding box of the table
                bbox = table.bbox
                cropped_page = page.crop(bbox)
                image_obj = cropped_page.to_image(resolution=300, antialias=True)
                image_obj.save(os.path.join(tmp_path, f"table_{i}-{table_idx}.png"), format="PNG", optimize=True, quantize=False)
                caption_candidates = captions[i + 1]
                caption_coords = []
                caption_texts = []
                for candidate in caption_candidates:
                    # check if any word of the COMMON_IMAGE_CAPTIONS is in the text
                    if any([word in candidate['text'][:30].lower() for word in COMMON_IMAGE_CAPTIONS]):
                        caption_coords.append(candidate['coordinates'])
                        caption_texts.append(candidate['text'])
                if not caption_coords:
                    print(f'No caption found for table {i}-{table_idx}')
                    print()
                    continue
                else:
                    ranked_indices = rank_captions(image_bbox, caption_coords)
                    caption_text = caption_texts[ranked_indices[0]]
                    print(f'Table {i}-{table_idx} is most likely to be captioned by this text: {caption_text}')
                    print()

def convert_to_dict(path_to_json):
    with open(path_to_json, 'r') as f:
        data = json.load(f)

    # Final dictionary to return
    result = {}

    for entry in data:
        page_number = entry["metadata"]["page_number"]
        text = entry["text"]
        points = entry["metadata"]["coordinates"]["points"]

        # Extract coordinates in the required format
        x_smallest = min(point[0] for point in points)
        y_smallest = min(point[1] for point in points)
        x_largest = max(point[0] for point in points)
        y_largest = max(point[1] for point in points)
        coordinates = [x_smallest, y_smallest, x_largest, y_largest]

        # Check if page_number already exists
        if page_number not in result:
            result[page_number] = []

        # Append the transformed data for the page_number
        result[page_number].append({
            "text": text,
            "coordinates": coordinates
        })

    return result


def rank_captions(image_bbox, text_bboxes):
    """
    Rank text blocks based on their likelihood of being the caption for a given image.

    Parameters:
    - image_bbox: (x0, top, x1, bottom) of the image
    - text_bboxes: List of bounding boxes [(x0, top, x1, bottom), ...] for text blocks

    Returns:
    - A list of indices from text_bboxes, ranked in descending probability of being the caption
    """
    img_center = ((image_bbox[0] + image_bbox[2]) / 2, (image_bbox[1] + image_bbox[3]) / 2)

    def distance_to_image(text_bbox):
        text_center = ((text_bbox[0] + text_bbox[2]) / 2, (text_bbox[1] + text_bbox[3]) / 2)
        return ((img_center[0] - text_center[0]) ** 2 + (img_center[1] - text_center[1]) ** 2) ** 0.5

    def position_weight(text_bbox):
        if text_bbox[3] < image_bbox[1]:  # text is above image
            return 0.7
        elif text_bbox[1] > image_bbox[3]:  # text is below image
            return 1.0
        elif text_bbox[2] < image_bbox[0]:  # text is to the left of image
            return 0.6
        elif text_bbox[0] > image_bbox[2]:  # text is to the right of image
            return 0.6
        else:
            return 0.3  # text overlaps with image, less likely to be a caption

    # Rank by distance and position
    rankings = [(i, distance_to_image(text_bbox) / position_weight(text_bbox)) for i, text_bbox in
                enumerate(text_bboxes)]

    # Sort by combined heuristic (lower value is more likely to be the caption)
    rankings.sort(key=lambda x: x[1])

    # Return ranked indices
    return [rank[0] for rank in rankings]
```

**Comment by theZaX** [comment] 2023-08-16 23:04
I opened this a while ago and I'm super happy you are working on it now!

One small request would be to have some way for me to get the actual images from inside of the document, this would be useful for further analysis or in my specific application we turn documents into eLearning, and so I would like to extract the images from the document during that process to use them in other places. 

I'm also interested in that sort of approach as LLMs become multimodal, that I could directly pass the image.

**Comment by hooman-bayer** [comment] 2023-08-16 23:07
Also my 2 cents here, if you could consider having it as modular as possible not only geared towards PDF. There are figures in docx, ppt other formats, so it would be great to slowly expand this to more file formats.

**Comment by Anaudia** [comment] 2023-11-06 08:47
Is there an update on this issue? I would love the option to work with the pictures directly and utilize some image-to-text models in my pipeline with unstructured.

**Comment by orlandounstructured** [comment] 2024-02-08 23:10
Closing because longer than 180 days; reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-08 23:10 UTC
Labels: enhancement
