### ISSUE TITLE
bug/reading html file returns  empty list

### ISSUE THREAD

**Issue by lwollenbergfuzzy** [Unstructured-IO/unstructured#3708] opened 2024-10-09 11:38 UTC
While reading html files we encountered the problem that we end up with an empty list.
 
Here is a small example:

```python
from unstructured.partition.html import partition_html
html_content="""
<!DOCTYPE html>
<html class="client-nojs" lang="de" dir="ltr">
<head>
</head>
<body>
  <div id="content" class="mw-body" role="main">
    <Seitenname>Bestellvorschläge weiterbearbeiten</Seitenname>
    <hr>
    <div class="content">
      <hauptteil_AB>
        <div class="rumpftabelle"></div>
        <table>
          <tbody>
            <tr>
              <th>Intern</th>
              <th>Feldwerte
              </th>
            </tr>
            <tr>
              <td>J</td>
              <td>Ja
              </td>
            </tr>
            <tr>
              <td>N</td>
              <td>Nein
              </td>
            </tr>
          </tbody>
        </table>
    </div>
    </hauptteil_AB>
    <fussteil_B></fussteil_B>
  </div>
  </div>
</body>
</html>
"""
elements = partition_html(text=html_content)
print(elements)
```
```python
out[0]: []
```

We would expect something like
```python
out[0]: [<unstructured.documents.elements.Title object>, <unstructured.documents.elements.Table object>]
```

We use version `0.15.13` of unstructured.

Through try and error, the problem seems to come from the custom tags `<hauptteil_AB>` and `<fussteil_B>`.
We appreciate any help on this issue.

**Comment by deku0818** [comment] 2024-10-12 06:24
The same problem.

**Comment by MiloMoerkerke** [comment] 2024-10-15 09:54
Same here

**Comment by PhorstenkampFuzzy** [comment] 2024-10-15 10:22
+1

**Comment by Prateek-coder19** [comment] 2024-10-24 22:11
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by PhorstenkampFuzzy** [comment] 2024-10-28 13:19
Anything new here? Even a coment would help on how to preporcess something like this.

**Comment by ajainfuzzy** [comment] 2024-10-28 14:10
+1

**Comment by jjleng** [comment] 2024-11-18 20:12
Same problem.

I guess the cause is here:
https://github.com/Unstructured-IO/unstructured/blob/ca27b8aa971663cf67f55ceeb15a2b768b601dee/unstructured/partition/html/parser.py#L841

It seems this is a feature, but it makes the HTML parser unable to parse custom HTML tags appropriately.

**Comment by scanny** [comment] 2024-12-18 06:33
Closing in place of feature request #3842. Feel free to add remarks or +1s there :)

**Closed by scanny** 2024-12-18 06:33 UTC
Labels: bug, html
