### ISSUE TITLE
`sent_tokenize` should fall back to splitting on punctuation if `punkt` isn't available

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#892] opened 2023-07-06 15:24 UTC
To give users an option for a slimmer installation, the goal of this issue is to update `sent_tokenize` to fall back to splitting on a punctuation regex if the NLTK `punkt` package is not installed.

**Comment by SimranJha2408** [comment] 2023-12-18 05:37
update?

**Comment by jscheel** [comment] 2024-01-04 16:31
This appears to be downloaded, even if you don't use any tokenization

**Comment by orlandounstructured** [comment] 2024-02-08 23:25
Closing because longer than 180 days; reopen with comment if the issue is still relevant

**Closed by orlandounstructured** 2024-02-08 23:25 UTC
